# Generated by Django 3.1.1 on 2021-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(max_length=1000),
        ),
    ]
